version: "3.9"

services:
  mongo:
    container_name: mongo-db
    image: mongo:focal
    expose:
      - 27017
    ports:
      - 27016:27017
    volumes:
      - ./db/mongo:/data/db
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 2
    restart: always
