version: "3.9"

services:
  mongo:
    container_name: mongo-db
    image: mongo:focal
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 2
    restart: always
